Menu:
  Home: /
  Archives: /archives/
  About: /about/
  Github: https://github.com/vevlins/
  RSS: /atom.xml

Site:
  Logo: img/logo.png
  Motto: Ponyo loves Sosuke! 

Intro:
  Avastar: img/avastar.jpg
  SNS:
    Weibo: ddd
    Zhihu: ddd
    Email: ddd

Comment:
  Id: xxxx
  Secret: xxx
  Repo: xxx
  Owner: xxx