Menu:
  Home: /
  Archives: /archives
  Github: https://github.com/vevlins
  RSS: /atom.xml
  About: /about
Site:
  Logo: img/logo.png
  Motto: Ponyo loves Sosuke! 

Intro:
  SNS:
    Weibo: 
    Zhihu: 
    Email: 
  Education: 
    Bachelor:
    Master:

Comment:
  Id: '8d83609a651e972e308d'
  Secret: 'db70b2bac2d75a88a78ebe04f556a0502cc3dd2b'
  Repo: 'Vevlins.github.io'
  Owner: 'Vevlins'