Menu:
  Home: /
  Archives: /archives/
  About: /about/
  Github: https://github.com/vevlins/
  RSS: /atom.xml

Site:
  Motto: Ponyo loves Sōsuke! 

Intro:
  Avastar: img/avastar.jpeg
  Name: Sōsuke
  Brief: aimed in front-end 
  SNS: 
    Weibo: ddd
    StackOverflow: 
    Github: https://github.com/Vevlins
    Pinterest: 
    Quora: 

CopyRight: 
  Author: Sōsuke
  License: CC BY-NC-SA 3.0 CN

Tip:
  Alipay: /img/qrcode.jpeg
  Wechat: /img/qrcode.jpeg

Comment:
  Id: 8d83609a651e972e308d
  Secret: db70b2bac2d75a88a78ebe04f556a0502cc3dd2b
  Repo: Vevlins.github.io
  Owner: Vevlins