Menu:
  Home: /
  Archives: /archives
  Github: https://github.com/vevlins
  RSS: /atom.xml

Site:
  Logo: img/logo.png

Intro:
  SNS:
    Weibo: 
    Zhihu: 
    Email: 
  Education: 
    Bachelor:
    Master:
    Phd:
  Work: [{
    Company: ,
    Title:
  }]

